export const UPDATE_POSTS = "UPDATE_POSTS";

// for login

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const SIGNOUT_USER = "SIGNOUT_USER";

export const CLEAR_ERROR_MSG = "CLEAR_ERROR_MSG";

export const EDIT_USER_SUCCESSFUL = "EDIT_USER_SUCCESSFUL";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";
