export const UPDATE_POSTS = "UPDATE_POSTS";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
// for login

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const SIGNOUT_USER = "SIGNOUT_USER";

export const CLEAR_ERROR_MSG = "CLEAR_ERROR_MSG";

export const EDIT_USER_SUCCESSFUL = "EDIT_USER_SUCCESSFUL";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";

// friends
export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const CLEAR_FRIEND_ARRAY = "CLEAR_FRIEND_ARRAY";
export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";

//Likes
export const UPDATE_POST_LIKE = "UPDATE_POST_LIKE";
export const UPDATE_COMMENT_LIKE = "UPDATE_COMMENT_LIKE";
export const FETCH_SEARCH_RESULTS_SUCCESS = "FETCH_SEARCH_RESULTS_SUCCESS";
